### ISSUE TITLE
Chức năng đăng ký/ đăng nhập

### ISSUE THREAD

**Issue by luanhytran** [luanhytran/ElectroPhoneStore#133]
# Phân tích chức năng đăng ký và đăng nhập
## Đăng nhập
- Admin và khách hàng đều có chức năng đăng nhập
- Admin là một tài khoản mặc định có sẵn nên sẽ đăng nhập được mà không cần đăng ký
- Khách hàng muốn đăng nhập được cần phải đăng ký và xác nhận tài khoản thành cônng 
- Khách hàng có chức năng khôi phục mật khẩu trong trường hợp quên mật khẩu đăng nhập
  - Khách hàng nhập email và hệ thống sẽ gửi mail khôi phục mật khẩu cho khách hàng
  - Khách hàng phải nhập đúng email đã dùng để đăng ký tài khoản
- Khách hàng và Admin đều có chức năng ghi nhớ đăng nhập
- Khi khách hàng đăng nhập có thể dùng các chức năng dành cho tài khoản đã đăng nhập như: _cập nhật thông tin cá nhân, đổi mật khẩu, xem lịch sử đặt hàng và đặt hàng_
## Đăng ký
- Một khách hàng sẽ cần đăng ký tài khoản khi muốn đặt hàng nhưng có tài khoản
- Khi đăng ký tài khoản thành công hệ thống sẽ gửi mail đến email xác nhận tài khoản đến email do khách hàng cung cấp
- Khách hàng buộc phải xác nhận tài khoản rồi mới đăng nhập được
## To-do
- [x] Đăng nhập cho Admin
- [x] Đăng nhập cho Khách hàng
- [x] Đăng ký cho khách hàng
- [x] Ghi nhớ đăng nhập
- [x] Khôi phục mật khẩu
- [x] Gửi mail khôi phục mật khẩu
- [x] Gửi mail xác nhận tài khoản
