### ISSUE TITLE
Chức năng đặt hàng phía khách hàng

### ISSUE THREAD

**Issue by luanhytran** [luanhytran/ElectroPhoneStore#137]
# Phân tích chức năng đặt hàng
- Chức năng này yêu cầu khách hàng phải đăng nhập
- Hình thức thanh toán mặc định là nhận hàng rồi mới thanh toán và hệ thống sẽ không hổ trợ thanh toán bằng ví điện tử
## Quy trình đặt hàng
- Khách hàng thêm sản phẩm vào giỏ hàng 
- Sau đó bấm nút tiến hành thanh toán, hệ thống sẽ kiểm tra khách hàng đăng nhập chưa, nếu chưa thì sẽ chuyển hướng sang trang đăng nhập
- Sau khi đăng nhập thì khách hàng có thể tiếp tục đặt hàng và chuyển hướng sang trang đặt hàng
- Trang đặt hàng có 3 mục là: thông tin giao hàng, thông tin thanh toán và tóm tắt sản phẩm sẽ đặt
  - Thông tin giao hàng:
    - Mặc định hệ thống sẽ hiển thị và lưu thông tin cá nhân của tài khoản khách hàng
    - Khách hàng có thể cập nhật thông tin giao hàng khi có nhu cầu giao đến người nào đó bằng cách cập nhật tên và số điện thoại người đó và cập nhật địa chỉ muốn giao hàng đến
    - Thông tin giao hàng không được để trống
  - Thông tin thanh toán:
    - Khách hàng có thể chọn 2 phương thức thanh toán là tiền mặt và thẻ tín dụng
    - Nếu chọn tiền mặt thì chỉ cần để nguyên và bấm đặt hàng, hệ thống sẽ lưu phương thức thanh toán là tiền mặt
    - Nếu chọn thẻ tín dụng thì sẽ hiển thị hộp thoại để khách hàng nhập thông tin thẻ như: mã thẻ, ngày hết hạn, mã bảo mật ...
  - Tóm tắt sản phẩm
    - Hiển thị các sản phẩm khách hàng đã thêm vào giỏ hàng và chuẩn bị đặt các sản phẩm đó
- Khi đặt hàng thành công, thì đơn hàng đó có trạng thái Đang chờ duyệt và sẽ hiển thị bên trang Danh sách đơn hàng phía admin để duyệt đơn hàng, phân tích chi tiết quá trình xử lý các đơn hàng của admin ở #130 
- Có mail thông báo cho admin biết khi đơn hàng mới cần duyệt
- Có mail thông báo đến hòm thư khách hàng khi đặt hàng thành công
## To-do
- [x] Chức năng hiển thị thông tin giao hàng mặc định của tài khoản
- [x] Chức năng cập nhật thông tin giao hàng cho khách hàng
- [x] Chức năng đặt hàng
- [x] Hiển thị tóm tắt sản phẩm
- [x] Email thông báo có đơn hàng mới cho admin
- [x] Email thông báo đặt hàng thành công đến hòm thư khách hàng
- [x] Thanh toán online
