### ISSUE TITLE
Chức năng quản lý thông tin phía khách hàng

### ISSUE THREAD

**Issue by luanhytran** [luanhytran/ElectroPhoneStore#141]
# Phân tích chức năng quản lý thông tin phía khách hàng
- Khách hàng có thể xem và cập nhật thông tin cá nhân của mình khi đăng nhập
  - Các thông tin như tên người dùng và email sẽ không được phép cập nhật
- Các thông tin cá nhân này được khách hàng cung cấp khi đăng ký tài khoản
- Khách hàng có thể thay đổi mật khẩu cho tài khoản
## To-do

- [x] Cập nhật thông tin cá nhân
- [x] Hiển thị thông tin cá nhân
- [x] Cập nhật mật khẩu
