### ISSUE TITLE
Chức năng xem lịch sử đơn hàng phía khách hàng

### ISSUE THREAD

**Issue by luanhytran** [luanhytran/ElectroPhoneStore#142]
# Phân tích chức năng xem lịch sử đơn hàng
- Khách hàng có thể xem lịch sử các đơn hàng đã và đang đặt của mình
- Khách hàng có thể hủy đơn hàng đang đặt khi đơn hàng ở trạng thái: Đang chờ duyệt và Đã duyệt nhưng chưa giao
- Khách hàng có thể xem chi tiết đơn hàng cụ thế
- Thông tin chi tiết đơn hàng bao gồm: _tên người đặt, tên người nhận, địa chỉ nhận, số điện thoại người nhận, ngày đặt, trạng thái đơn hàng và giá trị đơn hàng_
- Tính năng hiện thị các sản phẩm đã đặt sẽ phát triển sau
## To-do
- [x] Hủy đơn hàng
- [x] Xem chi tiết đơn hàng
- [x] Hiển thị danh sách đơn hàng đã và đang đặt ứng với tài khoản
